version: '3.9'

services:
  app:
    build:
      context: .
    container_name: app
    tty: true
    ports:
      - "8080:8080"
    volumes:
      - ./:/go/src/
      - ./go.mod:/go/src/go.mod
      - ./go.sum:/go/src/go.sum